version: 0.2

phases:
  pre_build:
    commands:
      - echo ASPNETCORE_ENVIRONMENT is $ASPNETCORE_ENVIRONMENT
      - echo Restore started on `date`
      - dotnet restore src/Blab.Api/src/Blab.Api/Blab.Api.csproj --source "https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/audacia/Audacia.Public/_packaging/AudaciaPublic/nuget/v3/index.json"
      - dotnet restore src/Blab.Api/src/Blab.Identity/Blab.Identity.csproj --source "https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/audacia/Audacia.Public/_packaging/AudaciaPublic/nuget/v3/index.json"
      - cd ./src/Blab.Ui/
      - npm install --include=dev
      - cd ../..
  build:
    commands:
      - echo Build started on `date`
      # api build
      - dotnet publish -c release -o ./build_output/api src/Blab.Api/src/Blab.Api/Blab.Api.csproj
      # identity build
      - dotnet publish -c release -o ./build_output/id src/Blab.Api/src/Blab.Identity/Blab.Identity.csproj
      # ui build
      - cd ./src/Blab.Ui/
      - npm run build-only
      - cd ../..
      - mv ./src/Blab.Ui/dist/blab-ui ./build_output/ui
      # moving configs
      - mv ./build_config/id/.platform -t ./build_output/id/
      # # for debugging
      # - ls ./build_output/api 
      # - ls ./build_output/ui 
      - ls ./build_output/id -a
  # post_build:
  #   commands:
  #     # update db context
  #     - echo Update database on `date`
  #     - dotnet ef database update --startup-project Blab.Api --project Blab.DataAccess --context BlabDbContext
  #     # update db context - openiddict
  #     - echo Update database on `date`
  #     - dotnet ef database update --startup-project Blab.Identity --project Blab.DataAccess --context OpenIddictDbContext
  #     # install openiddict seeding tool
  #     - dotnet new tool-manifest --force
  #     - dotnet tool install Audacia.Auth.OpenIddict.Seeding.EntityFrameworkCore --version 1.4.9 --add-source https://pkgs.dev.azure.com/audacia/Audacia.Public/_packaging/AudaciaPublic/nuget/v3/index.json
  #     # run openiddict seeding
  #     - echo Run OpenIddict Seeding
  #     - dotnet tool run openiddict-efcore-seeding "./build_output/id" "Blab.Identity" "int" "OpenIddictDbContext"
artifacts:
  files:
    - './build_output/*'
  secondary-artifacts:
    api:
      base-directory: './build_output/api'
      files:
        - '**/*'
      name: api
    identity:
      base-directory: './build_output/id'
      files:
        - '**/*'
      name: identity
    ui:
      base-directory: './build_output/ui'
      files:
        - '**/*'
      name: ui