name: 'Deploy Stage'
description: ''

inputs:
  aws-access-key-id:
    required: true
    type: string
  aws-access-key-secret:
    required: true
    type: string
  environment-name: # Name of the environment e.g. 'Quality Assurance' or 'User Acceptance'
    required: true
    type: string
  environment-id: # Id of the environment e.g. 'qa' or 'uat'
    required: true
    type: string

runs:
  using: "composite"
  steps:
  # # variable sub for app settings
  # - name: 'App Settings Variable Substitution'
  #   uses: microsoft/variable-substitution@v1
  #   with:
  #     files: '**/appsettings.json'
  #   env:
  #     AuthenticationConfig.ClientId: 'blab-api'
  #     AuthenticationConfig.ClientSecret: ${{ secrets.APPSETTINGS_AUTHENTICATION_CONFIG_CLIENT_ID }}

  # variable sub for .env
  # variable sub for web.qa.config etc.

  - name: Install dotnet ef tool
    shell: bash
    run: | 
      dotnet tool install --global dotnet-ef
      dotnet tool restore
  - name: 'Apply EF Core migrations - BlabDbContext'
    shell: bash
    run: dotnet ef database -c BlabDbContext -p Blab.DataAccess -s Blab.Identity

  - name: 'Apply EF Core migrations - OpenIddictDbContext'
    shell: bash
    run: dotnet ef database -c OpenIddictDbContext -p Blab.DataAccess -s Blab.Identity

    # uses: benday-inc/deploy-ef-core-migration@v1.1
    # with:
    #   # Path to directory that contains all the files
    #   path_to_directory: 'blab.identity'
    #   # DLL that contains the EF migrations to deploy
    #   migrations_dll: 'Blab.DataAccess.dll'
    #   # Root namespace for the EF migrations
    #   migrations_namespace: 'Blab.DataAccess'
    #   # DLL to start deploying migrations from. If you are publishing migrations from a web project, choose the web project DLL.  Otherwise, choose the migration DLL.
    #   startup_dll: 'Blab.Identity.dll'
    #   # Class name of the DbContext
    #   dbcontext_class_name: 'BlabDbContext'

  # - name: 'Apply EF Core migrations - OpenIddictDbContext'
  #   uses: benday-inc/deploy-ef-core-migration@v1.1
  #   with:
  #     # Path to directory that contains all the files
  #     path_to_directory: 'blab.identity'
  #     # DLL that contains the EF migrations to deploy
  #     migrations_dll: 'Blab.DataAccess.dll'
  #     # Root namespace for the EF migrations
  #     migrations_namespace: 'Blab.DataAccess.OpenIddict'
  #     # DLL to start deploying migrations from. If you are publishing migrations from a web project, choose the web project DLL.  Otherwise, choose the migration DLL.
  #     startup_dll: 'Blab.Identity.dll'
  #     # Class name of the DbContext
  #     dbcontext_class_name: 'OpenIddictDbContext'

  - name: 'Deploy Web'
    uses: ./.github/actions/deployment/aws/s3-bucket
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-access-key-secret: ${{ inputs.aws-access-key-secret }}
      application-name: 'blab-ui'
      paths: 'blab-ui'
      
  - name: 'Deploy Api'
    uses: ./.github/actions/deployment/aws/elastic-beanstalk
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-access-key-secret: ${{ inputs.aws-access-key-secret }}
      application-name: 'Blab.Api'
      environment-name: ${{ inputs.environment-name }}
      deployment-package: 'blab-api'

  - name: 'Deploy Identity'
    uses: ./.github/actions/deployment/aws/elastic-beanstalk
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-access-key-secret: ${{ inputs.aws-access-key-secret }}
      application-name: 'Blab.Identity'
      environment-name: ${{ inputs.environment-name }}
      deployment-package: 'blab-identity'
