



name: 'Deploy to Elastic BeanStalk'
description: 'Deploys an artifact to an AWS Elastic BeanStalk instance'

inputs:
  aws-access-key-id:
    required: true
    type: string
  aws-access-key-secret:
    required: true
    type: string
  bucket-name:
    required: true
    type: string
  application-name:
    required: true
    type: string
  environment-name:
    required: false
    type: string
  region:
    required: false
    type: string
    default: 'eu-west-2' # London
  deployment-package:
    required: true
    type: string

runs:
  using: "composite"
  steps:  
  - name: Deploy to Elastic BeanStalk
    uses: einaregilsson/beanstalk-deploy@v21
    with:
      existing_bucket_name: ${{ inputs.bucket-name }}
      aws_access_key: ${{ inputs.aws-access-key-id }} # stored in secrets section of the Github repo
      aws_secret_key: ${{ inputs.aws-access-key-secret }} # stored in secrets section of the Github repo
      application_name: ${{ inputs.application-name }}
      environment_name: ${{ inputs.environment-name }}
      region: ${{ inputs.region }}
      version_label: 1
      deployment_package: ${{ inputs.deployment-package }} # this is the name of the artifact directory, this may need to be a .zip - https://github.com/einaregilsson/beanstalk-deploy