



name: 'Deploy to an AWS S3 Bucket'
description: 'Deploys an artifact to an AWS S3 bucket'

inputs:
  aws-access-key-id:
    required: true
    type: string
  aws-access-key-secret:
    required: true
    type: string
  bucket-name:
    required: true
    type: string
  # application-name:
  #   required: true
  #   type: string
  region:
    required: false
    type: string
    default: 'eu-west-2' # London
  paths:
    required: true
    type: string
  # ignore-paths:
  #   required: false
  #   type: string
  #   default: ''

runs:
  using: "composite"
  steps:
  # - name: Configure AWS details
  #   uses: aws-actions/configure-aws-credentials@v1
  #   with:
  #     aws-access-key-id: ${{ inputs.aws-access-key-id }}
  #     aws-secret-access-key: ${{ inputs.aws-access-key-secret }}
  #     aws-region: ${{ inputs.region }}
  - name: Configure AWS details
    uses: shallwefootball/s3-upload-action@master
    with:
      aws_key_id: ${{ inputs.aws-access-key-id }}
      aws_secret_access_key: ${{ inputs.aws-access-key-secret }}
      aws_bucket: ${{ inputs.bucket-name }}
      source_dir: ${{ inputs.paths }}
      destination_dir: '/'
