name: Build and Deploy to the QA env

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: windows-latest
    environment: qa

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: LS output after checkout
      run: ls 
    - uses: ./.github/actions/stages/build
      with:
        nuget-feed-name: ${{ vars.NUGET_FEED_NAME }}
        nuget-feed-source: ${{ vars.NUGET_FEED_SOURCE }}
        azure-devops-token: '${{ vars.AZURE_DEVOPS_TOKEN }}'
    
  deploy-qa:
    needs: build # Step for needing jobs.build to be done before
    if: false # disabled for now
    runs-on: windows-latest
    environment: qa

    steps:
    - uses: ./.github/actions/stages/deploy
      with:
        environment-name: 'Quality Assurance'
        environment-id: 'qa'