on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ls 
    - uses: ./.github/actions/stages/build
    
  deploy-qa:
    needs: build # Step for needing jobs.build to be done before
    if: false # disabled for now
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/stages/deploy
      with:
        environment-name: 'Quality Assurance'
        environment-id: 'qa'