on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: ./../.github/actions/stages/build.stage
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
    - uses: ./../.github/actions/stages/deploy.stage
      with:
        environment-name: 'Quality Assurance'
        environment-id: 'qa'