on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: LS output after checkout
      run: ls 
    - uses: ./.github/actions/stages/build
      secrets:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
    
  deploy-qa:
    needs: build # Step for needing jobs.build to be done before
    if: false # disabled for now
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/stages/deploy
      with:
        environment-name: 'Quality Assurance'
        environment-id: 'qa'