on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ./stages/build.stage.yaml@template
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
    - uses: ./stages/deploy.stage.yaml@template
      with:
        environment-name: 'Quality Assurance'
        environment-id: 'qa'